// All action types used

export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const FETCH_CATEGORIES = 'FETCH_CATEGORIES';
export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS';
export const FETCH_CATEGORIES_ERROR = 'FETCH_CATEGORIES_ERROR';

export const FETCH_BOOKLIST = 'FETCH_BOOKLIST';
export const FETCH_BOOKLIST_SUCCESS = 'FETCH_BOOKLIST_SUCCESS';
export const FETCH_BOOKLIST_ERROR = 'FETCH_BOOKLIST_ERROR';

export const SELECT_CATEGORY = 'SELECT_CATEGORY';